### ISSUE TITLE
Additional filters to show only actively downloading/seeding

### ISSUE THREAD

**Issue by enchained** [seansfkelley/nas-download-manager#179]
I have a few dead downloads where I'm just hoping that the seed will return someday (it happens sometimes). Usually, I do not want to see those on the list, but currently have no way to filter them out (they have no errors, just marked as Downloading). Also, it will be really useful to see only active uploads for Completed, in case I want to shut down the server or limit the speed - I want to make sure it won't interrupt seeding to someone.

**Comment by seansfkelley** [comment]
How would a "hide inactive tasks" checkbox in the display/filter settings do for this?
