### ISSUE TITLE
Impossible to add new download on DSM 5.2

### ISSUE THREAD

**Issue by n31luj** [seansfkelley/nas-download-manager#189]
### Description

With version 0.10.1, when adding a new download on an old Synology DS110J (using the latest DSM version available 5.2-5967 Update 9), it fails with an error notification "Failed to add download The requested version does not support this functionality.".

When forcing the browser to use the version 0.9.3, everything works correctly (download is added in DownloadStation and the download is performed).

### Steps to Reproduce the Issue

1. Use version 0.10.1 (also 0.10.0) installed on Firefox 88.0 (Ubuntu 20.04.2) and configured (https + port 5001, or http + port 5000) to access an old Synology DS110J with latest DSM (5.2-5967 Update 9)
2. Right-click on a link (a torrent file in my case) and choose "Download with DownloadStation"
3. The download is not added on DownloadStation and a notification error appears ""Failed to add download The requested version does not support this functionality."

### Failure Logs

```
There is no "Debugging Output" section at the bottom of the extension's setting page.
```

### Versions

**Extension version**: 0.10.1 and also 0.10.0

**Browser version**: Firefox 88.0 on Ubuntu 20.04.2

**DSM version**: 5.2-5967 Update 9 (latest for DS110J)

**Comment by n31luj** [comment]
Here is a screenshot of the debugging information from 0.10.2 version:
![2021-05-10_11-51-28](https://user-images.githubusercontent.com/83905899/117641464-7749ee80-b186-11eb-8235-2832f380150d.png)

**Comment by Fano58** [comment]
Hello,

I have the exact same problem, since I installed version 0.11.1 on chrome

**Comment by bertrand-benoit** [comment]
Same issue with FF 93.0 (64 bits), and version 0.11.1 of this extension, when trying to add task for anything.

When checking debug information, this is what I see:
```
task add result 
Object { error: {…}, success: false, meta: {…} }
​
error: Object { code: 406 }
​​
code: 406
​​
<prototype>: Object { … }
​
meta: Object { apiGroup: "DownloadStation", apiSubgroup: "DownloadStation.Task", method: "create", … }
​​
apiGroup: "DownloadStation"
​​
apiSubgroup: "DownloadStation.Task"
​​
method: "create"
​​
version: 1
​​
<prototype>: Object { … }
​​​
__defineGetter__: function __defineGetter__()
​​​
__defineSetter__: function __defineSetter__()
​​​
__lookupGetter__: function __lookupGetter__()
​​​
__lookupSetter__: function __lookupSetter__()
​​​
__proto__: 
​​​
constructor: function Object()
​​​
hasOwnProperty: function hasOwnProperty()
​​​
isPrototypeOf: function isPrototypeOf()
​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​
toLocaleString: function toLocaleString()
​​​
toString: function toString()
​​​
valueOf: function valueOf()
​​​
<get __proto__()>: function __proto__()
​​​​
length: 0
​​​​
name: "get __proto__"
​​​​
<prototype>: function ()
​​​​​
apply: function apply()
​​​​​
arguments: 
​​​​​
bind: function bind()
​​​​​
call: function call()
​​​​​
caller: 
​​​​​
constructor: function Function()
​​​​​
length: 0
​​​​​
name: ""
​​​​​
toString: function toString()
​​​​​
Symbol(Symbol.hasInstance): function Symbol.hasInstance()
​​​​​
<get arguments()>: function arguments()
​​​​​
<set arguments()>: function arguments()
​​​​​
<get caller()>: function caller()
​​​​​
<set caller()>: function caller()
​​​​​
<prototype>: Object { … }
​​​
<set __proto__()>: function __proto__()
​
success: false
​
<prototype>: Object { … }
​​
__defineGetter__: function __defineGetter__()
​​​
length: 2
​​​
name: "__defineGetter__"
​​​
<prototype>: function ()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
​​​
length: 1
​​​
name: "set __proto__"
​​​
<prototype>: function ()
index.js:270:936
```

This 406 HTTP Status is very curious.

**Comment by seansfkelley** [comment]
@n31luj I've only now found some spare time to work on this project again. Are you still having this issue? It appears that the extension is trying to use the DSM 7.0-compatible Download Station endpoints, which almost certainly don't also exist on DSM 5 (they do on DSM 6.2.4 though). The extension is supposed to check before it tries to use it.

If you could dig around in some more logs, that would be really helpful. You can open the dev tools by opening the URL `about:devtools-toolbox?id=%7Bb17c0686-033c-4d03-b526-b16c99998c98%7D&type=extension`. After they're open, try to add the download. (It has to be a .torrent or .nzb file; magnet URLs and such won't use this code.) I'm looking for the network request where the extension asks the NAS what it's capable of. See the image below for how to do that (on extension version 0.10.1 or later, of course).

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/2101409/140624563-fb175129-4f52-437a-972e-d4c501ff614b.png">

**Comment by seansfkelley** [comment]
@bertrand-benoit that's not HTTP 406, that's Synology-internal-error-reporting 406, which probably means you don't have a default destination set in Download Station for the account you're using. Did the extension not report that in human-readable format in the popup? (It could also be a File Station error 406, but that's unlikely.)

**Comment by n31luj** [comment]
@ seansfkelley Here are two screenshots as requested from version 0.10.1 and 0.11.1

![NAS_Download_Manager_0-10-1](https://user-images.githubusercontent.com/83905899/141011924-aebc5d1e-3f4b-4aa0-addf-acb0a6aa6fc7.png)

![NAS_Download_Manager_0-11-1](https://user-images.githubusercontent.com/83905899/141011940-878dea46-5bae-4e70-9b0f-af584ac727a4.png)

**Comment by bertrand-benoit** [comment]
> @bertrand-benoit that's not HTTP 406, that's Synology-internal-error-reporting 406, which probably means you don't have a default destination set in Download Station for the account you're using. Did the extension not report that in human-readable format in the popup? (It could also be a File Station error 406, but that's unlikely.)

My Download Station is perfectly working when I add the links directly inside it from Nas DSM; and yes there is a default destination directory defined.
I don't see any corresponding option on the extension.

>  try to add the download. (It has to be a .torrent or .nzb file; magnet URLs and such won't use this code.)
What about other type of download (like uptobox for instance) ?

> added a commit that referenced this issue
Does it fix the issue, or only prevent the extension to request a DSM 6.x version?
Atm, on my side the extension still does not work, which version do you recommend for the extension, and for the Nas DSM?

Thanks.

**Comment by bertrand-benoit** [comment]
I have now a new issue, I can't configure the extension to use http (only local network), instead of https; and with https, it fails because it considers the auto-signed NAS Synology certificate as insecure ...
How can I unlock this situation?

**Comment by seansfkelley** [comment]
https://github.com/seansfkelley/nas-download-manager/blob/master/FAQ.md#why-cant-i-use-http-not-https-to-connect-to-the-nas
