### ISSUE TITLE
DSM 7 unable to connect

### ISSUE THREAD

**Issue by jerrevds** [seansfkelley/nas-download-manager#196]
Update from DSM 6.2 to DSM7.

When trying to connect the plugin mentions;
Connection failed for an unknown reason

**Comment by seansfkelley** [comment]
Can you provide any of the information that the issue template asked you for?

**Comment by jerrevds** [comment]
-all systems were rebooted during the night and now it seems to work. Althought I tested it with the same settings yesterday


### Description

Can(t connect to NAS

### Steps to Reproduce the Issue

1. Open the app
2. try to connect (test and save)
3. connection failed due to unknown reason

### Failure Logs

```
Check the bottom of the extension's setting page for a "Debugging Output" section and paste it over this text. If there is no such section in the settings, please say so.
```
no such button

### Versions

**Extension version**: (visible in NAS Download Manager's settings (Firefox) or in the extension list (Chrome))
0.11.1

**Browser version**: (usually found in the browser's "About")
chome: 92.0.4515.107

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)

DSM 7.0-41890
