### ISSUE TITLE
URL link, right click advanced context menu, save to folder option

### ISSUE THREAD

**Issue by BR-70** [seansfkelley/nas-download-manager#214]
I propose an additional context menu item (on right click on a link) which would allow the user to select a folder to which the new file will be downloaded. See screenshot, taken from another Web browser add-in.
![download to folder option](https://user-images.githubusercontent.com/95026581/143428439-7ee4a413-10d6-4f20-8d8c-7e83e9338adf.jpg)

**Comment by seansfkelley** [comment]
Thanks for the suggestion! This is already tracked at #128.
