### ISSUE TITLE
It can't login to NAS anymore

### ISSUE THREAD

**Issue by h-valenti** [seansfkelley/nas-download-manager#220]
### Description

Since like a week ago, I cannot login to NAS. I have not changed anything in my setup and my NAS credentials are correct, but this is what it shows to me:
![image](https://user-images.githubusercontent.com/98758383/151826284-836e7177-ba34-4e92-9c5c-3c86d32fa1e8.png)
While in settings page, it shows:
![image](https://user-images.githubusercontent.com/98758383/151826001-621d2100-ccb8-467c-964d-ee0390e3bd90.png)

### Failure Logs
Not such a thing.

[Check the bottom of the extension's setting page for a "Debugging Output" section and paste it over this text. If there is no such section in the settings, please say so.]

### Versions

**Extension version**: 0.12.0
**Browser version**: 96.0.3
**DSM version**: DSM 6.2.4-25556 Update 3

**Comment by seansfkelley** [comment]
This could be because of the mandatory switch to HTTPS. https://github.com/seansfkelley/nas-download-manager/issues/208#issuecomment-976771740

Can you ensure you've got your HTTPS settings/certificate correct?

**Comment by h-valenti** [comment]
You are right! Thank you very much!
