### ISSUE TITLE
Connection failed for an unknown reason DSM7

### ISSUE THREAD

**Issue by Siaomo** [seansfkelley/nas-download-manager#230]
I want to use this to download but I still can't get in with my login IP and user password, it shows Connection failed for an unknown reason. Is there something I did wrong? I'm sorry I'm using a translator, but I'm not very good at English and I may not be able to express myself very well.

![螢幕擷取畫面 2022-07-19 092445](https://user-images.githubusercontent.com/78332860/179644610-de21533f-c70f-419f-a7ab-ce5bb0fa5618.png)

![螢幕擷取畫面 2022-07-19 092500](https://user-images.githubusercontent.com/78332860/179644623-56027250-ab4a-4dcb-b020-f5afa8ff14bb.png)

![螢幕擷取畫面 2022-07-19 092932](https://user-images.githubusercontent.com/78332860/179644634-e8ed6dc8-5cbd-426d-a7da-d5008aef71e6.png)

![螢幕擷取畫面 2022-07-19 093026](https://user-images.githubusercontent.com/78332860/179644641-a9a942d8-7df6-40fb-b50e-0b746b579906.png)

**Comment by seansfkelley** [comment]
5000 is the default HTTP port, but it can only talk HTTPS. Did you try 5001 instead (which is the default HTTPS port)? You'll need to make sure you [accept the certificate](https://github.com/seansfkelley/nas-download-manager/blob/master/FAQ.md#what-is-an-invalid-certificate) in your browser.

**Comment by Siaomo** [comment]
Well my problem was somehow solved thanks to idk how i fix this work so ~now work thanks~
