### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by SpaceDaddy01** [seansfkelley/nas-download-manager#232]
Hello,
My internet provider will soon only allow IPv6 NAT settings; is there a way to configure NAS Download Manager with IPv6 addresses?
Thanks,
SD

**Comment by seansfkelley** [comment]
What happens if you try to put an IPv6 address in the hostname settings field? It works with IPv4, but I don't have an IPv6 setup I can try it out on.

**Comment by SpaceDaddy01** [comment]
Thanks, yes it seems to work with the IPv6 address in brackets. I left the
port number (since mandatory) although my understanding is that it is no
longer required in IPv6.

Sebastien

**Comment by seansfkelley** [comment]
Glad to hear it!
