### ISSUE TITLE
DevTools console failed to load source map: Could not load content for chrome-extension://iaijio... System error: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Dmytro2V** [seansfkelley/nas-download-manager#234]
### Description
DevTools failed to load source map: Could not load content for chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/content/index.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
A brief description of the issue.

### Steps to Reproduce the Issue
Just look into console after any page refresh. NAS is accessible, extension on page allowed.

1. Do something.
2. Do a different thing.
3. Expected error.

### Failure Logs

```
Check the bottom of the extension's setting page for a "Debugging Output" section and paste it over this text. If there is no such section in the settings, please say so.
```

### Versions

**Extension version**: (visible in NAS Download Manager's settings (Firefox) or in the extension list (Chrome))
0.12.1

**Browser version**: (usually found in the browser's "About")
Chrome 110.0.5481.105  official
**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
6x

**Comment by seansfkelley** [comment]
These are harmless and can be ignored. In any case, I pushed a change (741c52bb8d05a73b76e80b0098c2e75807322b5f) to avoid generating them since it's not classy to do so, which will be released in the next version.

**Comment by Dmytro2V** [comment]
Thanks. It was interfering with DOM study using console.log. 
For a while removed the message by setting 'on-press-only' in the extention settings.
